name: Build and Deploy Next.js with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NEXT_IMAGE_NAME: odey114/askme-nextjs
  DOCKER_REGISTRY: odey114/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Setup pnpm (needed for lockfile validation)
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      # Cache pnpm modules (optional, speeds up Docker build)
      - name: Cache pnpm modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            node_modules
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Docker Setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push (Docker handles the build)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' && true || false }}
          tags: ${{ env.NEXT_IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64