name: Build, Test, and Deploy Next.js with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NEXT_IMAGE_NAME: odey114/askme-nextjs
  DOCKER_REGISTRY: odey114/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'  # Uses pnpm-lock.yaml for caching
          cache-dependency-path: pnpm-lock.yaml

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      # Build the Next.js app
      - name: Build Next.js app
        run: pnpm build

      # Docker Setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' && true || false }}
          tags: ${{ env.NEXT_IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
